version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    image: astrosphere_server
    container_name: node_server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env.local
    image: astrosphere_client
    container_name: nextjs_client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mongo_data:
